tls.host=localhost
tls.port=31337
#tls.port=8443
tls.amountTLSRequests=100
tls.threadsAmount=4
tls.requestTimeout=100

dashboard.browser.enabled=true
dashboard.browser.port=8080
dashboard.browser.https.enabled=false
dashboard.browser.https.keystore=
dashboard.browser.https.keystorePassword=

data.random.minSizeArray=0
data.random.maxSizeArray=10000
data.random.arraySize=1000
